# -*- mode: ruby -*-
# vi: set ft=ruby :

# Specify minimum Vagrant version and Vagrant API version
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

# Plugins we require
required_plugins = %w(vagrant-junos vagrant-vbguest)

##### START Helper functions
def install_ssh_key()
  puts "Adding ssh key to the ssh agent"
  puts "ssh-add #{Vagrant.source_root}/keys/vagrant"
  system "ssh-add #{Vagrant.source_root}/keys/vagrant"
end

def install_plugins(required_plugins)
  plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }
  if not plugins_to_install.empty?
    puts "Installing plugins: #{plugins_to_install.join(' ')}"
    if system "vagrant plugin install #{plugins_to_install.join(' ')}"
      exec "vagrant #{ARGV.join(' ')}"
    else
      abort "Installation of one or more plugins has failed. Aborting."
    end
  end
end
##### END Helper functions

# Install ssh key
install_ssh_key

# Check certain plugins are installed
install_plugins required_plugins

# Require YAML module
require 'yaml'
 
# Read YAML file with box details
hosts = YAML.load_file('hosts.yaml')

# Lab definition begins here
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vbguest.auto_update = false

  # Iterate through entries in YAML file
  hosts.each do |host|
    config.vm.define host["name"] do |srv|
      srv.vm.box = host["box"]

      host["forwarded_ports"].each do |port|
      srv.vm.network :forwarded_port, guest: port["guest"], host: port["host"], id: port["name"]
      end

      host["links"].each do |link|
      srv.vm.network "private_network", virtualbox__intnet: link["name"], ip: "169.254.1.11", auto_config: false
      end

    end
  end
end

