# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
   config.vm.box = "ubuntu/trusty64"

   config.vm.network "forwarded_port", guest: 80, host: 8080
   config.vm.network "forwarded_port", guest: 8990, host: 8990

   config.vm.provision "shell", inline: <<-SHELL
export DEBIAN_FRONTEND=noninteractive
sudo apt-get -y update
sudo apt-get -y install build-essential python-dev libffi-dev libssl-dev
sudo apt-get -y install python-pip
sudo pip install nsot==1.0.5
sudo pip install mrproxy
mkdir /home/vagrant/.nsot
nsot-server init /home/vagrant/.nsot/nsot.conf.py
chown -R vagrant:vagrant /home/vagrant/.nsot
sed -i "s/localhost/0.0.0.0/" /home/vagrant/.nsot/nsot.conf.py
nsot-server --config=/home/vagrant/.nsot/nsot.conf.py collectstatic --noinput
   SHELL

end
